In [4]:
import numpy as np


#Atividade de fixação
##Numpy

###1. Crie um array com 4 linhas e 3 colunas com valores aleatórios
arr = np.random.random((4,3))
arr


array([[0.33630337, 0.6480418 , 0.42551328],
       [0.12541755, 0.02035825, 0.98604959],
       [0.44689582, 0.58029048, 0.68116066],
       [0.09938099, 0.27233424, 0.23419178]])

In [5]:
###2.Crie um array com valores inteiros,3 linhas e 5 colunas com valores aleatórios.
np.random.randint(1,20, size=(3,5))

array([[ 8, 16, 18, 19, 11],
       [ 8,  9,  5, 12,  5],
       [ 8, 11,  4, 13, 11]])

In [9]:
np.arange(0,90,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

In [13]:
arr57 = np.random.randint(1,30, size=(5,7))
arr57.flatten()

array([18, 16, 18, 19, 29, 10,  4, 24, 13, 24,  6,  1, 23, 29, 27, 11, 17,
       26, 12, 22, 14,  1, 13, 11,  8, 11, 21,  7, 28, 16, 29,  7, 12,  2,
        1])

In [15]:
bingo = np.random.randint(1,30, size=(10,4,3))
bingo

array([[[26, 21, 19],
        [ 2, 13, 17],
        [ 3, 19, 13],
        [17, 14, 12]],

       [[10,  2, 26],
        [ 6, 13, 29],
        [21,  4,  7],
        [24, 20,  7]],

       [[13, 20, 28],
        [13, 17, 29],
        [21, 15,  3],
        [27, 19, 15]],

       [[ 6, 21, 27],
        [25, 17,  3],
        [26, 28, 17],
        [18, 13, 27]],

       [[ 1,  9, 18],
        [ 2,  1, 21],
        [20, 14, 10],
        [ 7, 20,  8]],

       [[23, 15, 17],
        [ 1,  5, 20],
        [ 2, 26,  2],
        [25,  6,  5]],

       [[ 4, 22, 29],
        [17, 13, 26],
        [24,  2,  5],
        [19, 22, 19]],

       [[17, 13,  8],
        [13, 29, 29],
        [ 1, 24, 28],
        [ 1, 15,  7]],

       [[27, 17, 23],
        [28, 23,  9],
        [ 5, 16,  6],
        [ 8, 24,  7]],

       [[23,  3, 26],
        [ 9, 28, 19],
        [19, 17, 22],
        [20,  1,  5]]])

In [16]:
bingo.reshape(5,4,6)

array([[[26, 21, 19,  2, 13, 17],
        [ 3, 19, 13, 17, 14, 12],
        [10,  2, 26,  6, 13, 29],
        [21,  4,  7, 24, 20,  7]],

       [[13, 20, 28, 13, 17, 29],
        [21, 15,  3, 27, 19, 15],
        [ 6, 21, 27, 25, 17,  3],
        [26, 28, 17, 18, 13, 27]],

       [[ 1,  9, 18,  2,  1, 21],
        [20, 14, 10,  7, 20,  8],
        [23, 15, 17,  1,  5, 20],
        [ 2, 26,  2, 25,  6,  5]],

       [[ 4, 22, 29, 17, 13, 26],
        [24,  2,  5, 19, 22, 19],
        [17, 13,  8, 13, 29, 29],
        [ 1, 24, 28,  1, 15,  7]],

       [[27, 17, 23, 28, 23,  9],
        [ 5, 16,  6,  8, 24,  7],
        [23,  3, 26,  9, 28, 19],
        [19, 17, 22, 20,  1,  5]]])